version: "3"
services:
  glue:
    build: .
    depends_on:
      - localstack
      - db
      - db2
    ports:
      - "8888:8888"
      - "8089:8080"

    environment:
      - AWS_ACCESS_KEY_ID=dummy
      - AWS_SECRET_ACCESS_KEY=dummy
      - AWS_REGION=ap-northeast-1
      - AWS_DEFAULT_REGION=ap-northeast-1
      - PGPASSWORD=test
    tty: true
    stdin_open: true

    command: /bin/bash

    volumes:
      # - ~/.aws:/home/ubuntu/.aws
      - .:/home/ubuntu/app

    working_dir: /home/ubuntu/app
  localstack:
    image: localstack/localstack-light:0.11.3
    ports:
      - "4566-4584:4566-4584"
      - "8080:8080"
    environment:
      - SERVICES=s3
      - DOCKER_HOST=unix:///var/run/docker.sock
      - DEFAULT_REGION=ap-northeast-1

  db:
    image: mysql:8.0.23
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=test
    command: --default-authentication-plugin=mysql_native_password

  db2:
    image: postgres:13.1
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=test
